config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.6
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/RECETOX/gc_derivatization:
      branch: master
      repo: https://github.com/RECETOX/gc_derivatization
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/RECETOX/gc_derivatization git:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-chestnut-zonkey.sh
        container: qc.acc_ready-sangria-shark
  QC.Doc:
    repos:
      github.com/RECETOX/gc_derivatization find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-seashell-wrasse.sh
        container: qc.doc_lousy-salmon-binturong
      github.com/RECETOX/gc_derivatization git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-sangria-drever.sh
        container: qc.doc_lovely-pumpkin-rabbit
      github.com/RECETOX/gc_derivatization markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-ultramarine-magpie.sh
        container: qc.doc_seedy-cerulean-quokka
  QC.Lic:
    repos:
      github.com/RECETOX/gc_derivatization licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-cobalt-bracke.sh
        container: qc.lic_randy-jade-toad
  QC.Sec:
    repos:
      github.com/RECETOX/gc_derivatization bandit:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-gamboge-axolotl.sh
        container: qc.sec_goopy-peach-emu
  QC.Sty:
    repos:
      github.com/RECETOX/gc_derivatization flake8:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-harlequin-greyhound.sh
        container: qc.sty_lanky-charcoal-audemer
  QC.Ver:
    repos:
      github.com/RECETOX/gc_derivatization get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-denim-wolfhound.sh
        container: qc.ver_shabby-green-woodlouse
timeout: 1800
