config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.5
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/RECETOX/gc_derivatization:
      branch: master
      repo: https://github.com/RECETOX/gc_derivatization
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/RECETOX/gc_derivatization git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-teal-baboon.sh
        container: qc.acc_woozy-scarlet-malamute
  QC.Doc:
    repos:
      github.com/RECETOX/gc_derivatization find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-myrtle-numbat.sh
        container: qc.doc_flimsy-apricot-eagle
      github.com/RECETOX/gc_derivatization git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-myrtle-chinchilla.sh
        container: qc.doc_leaky-chartreuse-mayfly
      github.com/RECETOX/gc_derivatization markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-platinum-mule.sh
        container: qc.doc_homey-brown-goose
  QC.Lic:
    repos:
      github.com/RECETOX/gc_derivatization licensee:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-auburn-woodpecker.sh
        container: qc.lic_scummy-aquamarine-octopus
  QC.Sec:
    repos:
      github.com/RECETOX/gc_derivatization bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-tangerine-labradoodle.sh
        container: qc.sec_silly-maroon-hyena
  QC.Sty:
    repos:
      github.com/RECETOX/gc_derivatization flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-purple-bordeaux.sh
        container: qc.sty_goopy-eggplant-moorhen
  QC.Ver:
    repos:
      github.com/RECETOX/gc_derivatization get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-russet-mist.sh
        container: qc.ver_sickly-gamboge-llama
timeout: 1800
